# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-14 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudfly_heketi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pod',
            name='namespaces',
        ),
        migrations.RemoveField(
            model_name='pod',
            name='pvc',
        ),
        migrations.RemoveField(
            model_name='pv',
            name='namespaces',
        ),
        migrations.RemoveField(
            model_name='pvc',
            name='namespace',
        ),
        migrations.RemoveField(
            model_name='pvc',
            name='pv',
        ),
        migrations.RemoveField(
            model_name='pvc',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='heketi_node',
            name='managehost',
        ),
        migrations.RemoveField(
            model_name='heketi_node',
            name='storagehost',
        ),
        migrations.RemoveField(
            model_name='heketi_volume',
            name='backmounts',
        ),
        migrations.AddField(
            model_name='heketi_node',
            name='hostnames',
            field=models.CharField(max_length=128, null=True, verbose_name='HostName'),
        ),
        migrations.AlterField(
            model_name='heketi_auth',
            name='admin_key',
            field=models.CharField(default='My Secret', max_length=128, verbose_name='认证模式'),
        ),
        migrations.AlterField(
            model_name='heketi_volume',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='heketi_volume',
            name='nodes',
            field=models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='cloudfly_heketi.Heketi_Node', verbose_name='Nodes'),
        ),
        migrations.DeleteModel(
            name='Glusterfs',
        ),
        migrations.DeleteModel(
            name='NameSpaces',
        ),
        migrations.DeleteModel(
            name='Pod',
        ),
        migrations.DeleteModel(
            name='PV',
        ),
        migrations.DeleteModel(
            name='PVC',
        ),
    ]
